name: tdw-02-pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --cov=./tdw-02 --cov-report=json:./tdw-02/coverage/coverage.json

    - name: List coverage files
      run: |
        echo "Listing coverage files..."
        ls -R ./tdw-02/coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./tdw-02/coverage/*.json
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true